version: "3.9"

services:
  frontend:
    build:
      context: ./frontend       # было: .
      dockerfile: Dockerfile
    container_name: valentines-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:4000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: valentines-backend
    ports:
      - "4000:4000"
    environment:
      # Используем root-пользователя, которого поднимает mongo-сервис
      MONGO_URL: "mongodb://root:example@mongo:27017/valentines?authSource=admin"
      NODE_ENV: "production"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: valentines-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: valentines
    volumes:
      - mongo_data:/data/db
    # Урезаем болтовню Mongo в логах
    command: ["--quiet"]

volumes:
  mongo_data:

